services:
  - type: web
    name: egchat-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: APP_VERSION
        value: "2.6.4"
