function buildSarPayload({ report = {}, subject = {}, alerts = [] } = {}) {
  const now = new Date().toISOString();
  return {
    schema: 'SIF-1.0',
    generated_at: now,
    reporting_entity: {
      name: 'EGCHAT',
      country: 'GQ',
    },
    report: {
      id: report.id || null,
      status: report.status || 'DRAFT',
      detected_at: report.detected_at || now,
      suspicious_reason: report.suspicious_reason || report.reason || 'AML alert generated by EGCHAT',
      amount: report.amount ?? null,
      currency: report.currency || 'XAF',
    },
    subject: {
      user_id: subject.user_id || subject.id || null,
      full_name: subject.full_name || null,
      phone: subject.phone || null,
      nationality: subject.nationality || null,
      kyc_risk_level: subject.risk_level || null,
    },
    alerts: alerts.map((alert) => ({
      rule_id: alert.id || alert.rule_id,
      severity: alert.severity,
      description: alert.description,
      created_at: alert.created_at || now,
    })),
  };
}

module.exports = { buildSarPayload };
